apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-cochise
spec:
  selector:
    matchLabels:
      volume: cochise
  resources:
    requests:
      storage: 5Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: ""

